<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Promises & CallBack-Hell</title>
  </head>
  <body>
    <script>
      // CallBack-Hell

      /*

      // Issue's with callback hell:-

       Inversion of control- loss the control of the function to some other function.  
      */

      function task1(callback){
          setTimeout(() => {
              console.log('Task1')
              callback();
          }, 1000);
      }

      function task2(callback){
          setTimeout(() => {
              console.log('Task2')
              callback();
          }, 2000);
      }
      function task3(callback){
          setTimeout(() => {
              console.log('Task3')
              callback();
          }, 5000);
      }
      function task4(callback){
          setTimeout(() => {
              console.log('Task4')
              callback();
          }, 3000);
      }
      function task5(callback){
          setTimeout(() => {
              console.log('Task5')
              callback();
          }, 4000);
      }
      function task6(callback){
          setTimeout(() => {
              console.log('Task6')
              callback();
          }, 700);
      }
      function task7(callback){
          setTimeout(() => {
              console.log('Task7')
              callback();
          }, 600);
      }
      function task8(callback){
          setTimeout(() => {
              console.log('Task8')
              callback();
          }, 500);
      }

      // task1 and along with other task functions are making callback hell pyramid by calling one another into each other.
      // to reduce it promises came into existence.

    //   task1(()=>{
    //       task2(()=>{
    //           task3(()=>{
    //               task4(()=>{
    //                   task5(()=>{
    //                       task6(()=>{
    //                           task7(()=>{
    //                               task8(()=>{

    //                               })
    //                           })
    //                       })
    //                   })
    //               })
    //           })
    //       })
    //   })

      // ---------------------------------------------------------------------------------------------------------------------------------

      // Promise -> A promise is an object in js that represents the eventual completion or rejection of an asynchrnous operation & its resulting value.  

      // Example-> Requesting some data from a server, the promise promises us to get that data which we can use in future.

      // States of promise -> Pending, resolve, rejected.

      // handlers of promise -> then("fulfillment handler") works for resolve & catch("Rejection handler") works for reject.

      // Basic syntax of promise is that it takes two parameters (ie resolve, reject) as an argument in the callback function provided to promise .

      


    /* Some Points to remember about Promise:-

    > All three methods (.then, .catch & .finally) returns a promise & can chain multiple promises also. 
    
    > these resolve & reject parameters come from the promise constructor which accepts callback as an argument & inside that callback we pass two functions that is resolve function & reject function. 
    
    */

  // Example of promises. 



  const NewPromise=new Promise((resolve, reject)=>{
    setTimeout(()=>{
        reject(1);
    },200);
  })
.then((data1)=>{
    console.log(data1);
    return 2;
  })

.then((data2)=>{
    console.log(data2);
    return 3;
  })
//   What if we put catch method between these then methods (where state is resolved) ?
// the catch method will not be executed, since because the promise is in resolve state, so for this case catch method will never execute. [1,2,3,4,finally 1,finally 2]. 

// What if we put catch method between these then methods (where state is rejected) ?
// the first catch method along with then methods coming after first catch will be executed rest all then & catch methods will not executed. [1,6,4.finally 1, finally 2]. 


.catch((error)=>{
    console.log(error);
    return 6;
  })

.then((data3)=>{
    console.log(data3);
    return 4;
  })
.then((data4)=>{
    console.log(data4);
    return 5;
})
.finally(()=>{
    console.log("finally 1");
})
.finally(()=>{
    console.log("finally 2");
})









      
    </script>
  </body>
</html>
